py_binary(
    name = "create_combined_runtime",
    srcs = ["create_combined_runtime.py"],
    #    deps = [],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "windows_jni_loader",
    srcs = ["WindowsLoaderHelper.dll"],
    visibility = ["//visibility:public"],
)
